Repository OCA/bank-statement-import, pull requests merged in 2018-12, with the labels that each got.

#185 [IMP] Let user choose date format of .qif file import
  account_bank_statement_import_qif/README.rst
  account_bank_statement_import_qif/__init__.py
  account_bank_statement_import_qif/__manifest__.py
  account_bank_statement_import_qif/models/__init__.py
  account_bank_statement_import_qif/models/account_journal.py
  account_bank_statement_import_qif/test_files/test_qif.qif
  account_bank_statement_import_qif/test_files/test_qif_dmy.qif
  account_bank_statement_import_qif/test_files/test_qif_ymd.qif
  account_bank_statement_import_qif/tests/test_import_bank_statement.py
  account_bank_statement_import_qif/views/account_journal_view.xml
  account_bank_statement_import_qif/wizards/account_bank_statement_import_qif.py
Labels: approved

#189 [11.0][FIX] account_bank_statement_import_camt_oca: add tag AddtlInf to the name field
  account_bank_statement_import_camt_oca/__manifest__.py
  account_bank_statement_import_camt_oca/models/parser.py
Labels: approved, ready to merge

#188 [FIX][account_bank_statement_import_save_file] don't mess with the registry for tests
  account_bank_statement_import_save_file/tests/test_save_file.py
Labels: approved, needs review

#190 [10.0][FIX] account_bank_statement_import_camt: add tag AddtlInf to the name field
  account_bank_statement_import_camt/__manifest__.py
  account_bank_statement_import_camt/models/parser.py
Labels: approved, ready to merge
