Repository OCA/bank-statement-import, pull requests merged in 2019-05, with the labels that each got.

#198 [12.0] [MIG] Account Bank Statement Import CAMT OCA
  .gitignore
  account_bank_statement_import_camt_oca/README.rst
  account_bank_statement_import_camt_oca/__init__.py
  account_bank_statement_import_camt_oca/__manifest__.py
  account_bank_statement_import_camt_oca/i18n/account_bank_statement_import_camt_oca.pot
  account_bank_statement_import_camt_oca/i18n/de.po
  account_bank_statement_import_camt_oca/i18n/es.po
  account_bank_statement_import_camt_oca/i18n/fa.po
  account_bank_statement_import_camt_oca/i18n/fi.po
  account_bank_statement_import_camt_oca/i18n/fr.po
  account_bank_statement_import_camt_oca/i18n/fr_CH.po
  account_bank_statement_import_camt_oca/i18n/gl.po
  account_bank_statement_import_camt_oca/i18n/hr.po
  account_bank_statement_import_camt_oca/i18n/lt_LT.po
  account_bank_statement_import_camt_oca/i18n/nb_NO.po
  account_bank_statement_import_camt_oca/i18n/nl.po
  account_bank_statement_import_camt_oca/i18n/pt_BR.po
  account_bank_statement_import_camt_oca/i18n/pt_PT.po
  account_bank_statement_import_camt_oca/i18n/sl.po
  account_bank_statement_import_camt_oca/models/__init__.py
  account_bank_statement_import_camt_oca/models/account_bank_statement_import.py
  account_bank_statement_import_camt_oca/models/account_journal.py
  account_bank_statement_import_camt_oca/models/parser.py
  account_bank_statement_import_camt_oca/readme/CONTRIBUTORS.rst
  account_bank_statement_import_camt_oca/readme/DESCRIPTION.rst
  account_bank_statement_import_camt_oca/static/description/index.html
  account_bank_statement_import_camt_oca/test_files/golden-camt053-no-ntry.pydata
  account_bank_statement_import_camt_oca/test_files/golden-camt053-txdtls.pydata
  account_bank_statement_import_camt_oca/test_files/golden-camt053.pydata
  account_bank_statement_import_camt_oca/test_files/test-camt053
  account_bank_statement_import_camt_oca/test_files/test-camt053-no-ntry
  account_bank_statement_import_camt_oca/test_files/test-camt053-txdtls
  account_bank_statement_import_camt_oca/test_files/test-camt053.zip
  account_bank_statement_import_camt_oca/tests/__init__.py
  account_bank_statement_import_camt_oca/tests/test_import_bank_statement.py
  account_bank_statement_import_camt_oca/views/account_bank_statement_import.xml
  setup/account_bank_statement_import_camt_oca/odoo/addons/account_bank_statement_import_camt_oca
  setup/account_bank_statement_import_camt_oca/setup.py
Labels: approved, ready to merge

#211 [11.0] [FIX] float parsing in paypal import
  account_bank_statement_import_paypal/data/paypal_map_data.xml
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_map.py
  account_bank_statement_import_paypal/tests/paypal_en.csv
  account_bank_statement_import_paypal/tests/test_paypal_statement_import.py
  account_bank_statement_import_paypal/views/paypal_map_views.xml
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal.py
Labels: approved, needs review

#207 [MIG] account_bank_statement_import_paypal: Migration to 12.0
  account_bank_statement_import_paypal/README.rst
  account_bank_statement_import_paypal/__init__.py
  account_bank_statement_import_paypal/__manifest__.py
  account_bank_statement_import_paypal/data/paypal_map_data.xml
  account_bank_statement_import_paypal/i18n/account_bank_statement_import_paypal.pot
  account_bank_statement_import_paypal/i18n/es.po
  account_bank_statement_import_paypal/models/__init__.py
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_map.py
  account_bank_statement_import_paypal/models/account_journal.py
  account_bank_statement_import_paypal/readme/CONFIGURE.rst
  account_bank_statement_import_paypal/readme/CONTRIBUTORS.rst
  account_bank_statement_import_paypal/readme/DESCRIPTION.rst
  account_bank_statement_import_paypal/readme/USAGE.rst
  account_bank_statement_import_paypal/security/ir.model.access.csv
  account_bank_statement_import_paypal/static/description/icon.png
  account_bank_statement_import_paypal/static/description/index.html
  account_bank_statement_import_paypal/static/description/paypal_backoffice.png
  account_bank_statement_import_paypal/tests/__init__.py
  account_bank_statement_import_paypal/tests/paypal_en.csv
  account_bank_statement_import_paypal/tests/test_paypal_statement_import.py
  account_bank_statement_import_paypal/views/account_journal_views.xml
  account_bank_statement_import_paypal/views/paypal_map_views.xml
  account_bank_statement_import_paypal/wizards/__init__.py
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal.py
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_view.xml
  account_bank_statement_import_paypal/wizards/create_map_lines_from_file.py
  account_bank_statement_import_paypal/wizards/create_map_lines_from_file_views.xml
Labels: approved, work in progress
