Repository OCA/bank-statement-import, pull requests merged in 2020-03, with the labels that each got.

#217 [12] [FIX] exception when using multiple files type
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal.py
Labels: approved

#236 [12.0][IMP] account_bank_statement_import_paypal
  account_bank_statement_import_paypal/README.rst
  account_bank_statement_import_paypal/__init__.py
  account_bank_statement_import_paypal/__manifest__.py
  account_bank_statement_import_paypal/data/maps.xml
  account_bank_statement_import_paypal/data/paypal_map_data.xml
  account_bank_statement_import_paypal/migrations/12.0.2.0.0/post-migration.py
  account_bank_statement_import_paypal/models/__init__.py
  account_bank_statement_import_paypal/models/account_bank_statement_import.py
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_map.py
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_mapping.py
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_parser.py
  account_bank_statement_import_paypal/models/account_journal.py
  account_bank_statement_import_paypal/readme/CONFIGURE.rst
  account_bank_statement_import_paypal/readme/CONTRIBUTORS.rst
  account_bank_statement_import_paypal/readme/DESCRIPTION.rst
  account_bank_statement_import_paypal/readme/HISTORY.rst
  account_bank_statement_import_paypal/readme/USAGE.rst
  account_bank_statement_import_paypal/security/ir.model.access.csv
  account_bank_statement_import_paypal/static/description/index.html
  account_bank_statement_import_paypal/static/description/paypal_backoffice.png
  account_bank_statement_import_paypal/tests/__init__.py
  account_bank_statement_import_paypal/tests/fixtures/activity_en.csv
  account_bank_statement_import_paypal/tests/fixtures/empty_activity.csv
  account_bank_statement_import_paypal/tests/fixtures/statement_en.csv
  account_bank_statement_import_paypal/tests/paypal_en.csv
  account_bank_statement_import_paypal/tests/test_account_bank_statement_import_paypal.py
  account_bank_statement_import_paypal/tests/test_paypal_statement_import.py
  account_bank_statement_import_paypal/views/account_bank_statement_import.xml
  account_bank_statement_import_paypal/views/account_bank_statement_import_paypal_mapping.xml
  account_bank_statement_import_paypal/views/account_journal_views.xml
  account_bank_statement_import_paypal/views/paypal_map_views.xml
  account_bank_statement_import_paypal/wizards/__init__.py
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal.py
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal_mapping_wizard.py
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal_mapping_wizard.xml
  account_bank_statement_import_paypal/wizards/create_map_lines_from_file.py
  account_bank_statement_import_paypal/wizards/create_map_lines_from_file_views.xml
Labels: approved, ready to merge

#265 [12.0][FIX] account_bank_statement_import_paypal: lost wizard
  account_bank_statement_import_paypal/views/account_bank_statement_import_paypal_mapping.xml
  account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal_mapping_wizard.xml
Labels: bot is merging ⏳

#266 [12.0][IMP] account_bank_statement_import_online: hide Create/Import statement
  account_bank_statement_import_online/__manifest__.py
  account_bank_statement_import_online/views/account_journal.xml
Labels: bot is merging ⏳

#234 [12.0][ADD] account_bank_statement_import_online_paypal
  account_bank_statement_import_online_paypal/__init__.py
  account_bank_statement_import_online_paypal/__manifest__.py
  account_bank_statement_import_online_paypal/models/__init__.py
  account_bank_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
  account_bank_statement_import_online_paypal/readme/CONFIGURE.rst
  account_bank_statement_import_online_paypal/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_paypal/readme/DESCRIPTION.rst
  account_bank_statement_import_online_paypal/readme/ROADMAP.rst
  account_bank_statement_import_online_paypal/readme/USAGE.rst
  account_bank_statement_import_online_paypal/tests/__init__.py
  account_bank_statement_import_online_paypal/tests/test_account_bank_statement_import_online_paypal.py
  account_bank_statement_import_online_paypal/views/online_bank_statement_provider.xml
Labels: approved, bot is merging ⏳, ready to merge
