Repository OCA/bank-statement-import, pull requests merged in 2021-07, with the labels that each got.

#399 [13.0][FIX] account_bank_statement_import_paypal: Parser bug for required fields
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_parser.py
Labels: approved, bot is merging ⏳

#398 [14.0] [MIG] account_statement_import_paypal: Migration to v14.0
  account_statement_import_paypal/README.rst
  account_statement_import_paypal/__init__.py
  account_statement_import_paypal/__manifest__.py
  account_statement_import_paypal/data/maps.xml
  account_statement_import_paypal/i18n/account_statement_import_paypal.pot
  account_statement_import_paypal/i18n/es.po
  account_statement_import_paypal/migrations/14.0.1.0.0/pre-migrate.py
  account_statement_import_paypal/models/__init__.py
  account_statement_import_paypal/models/account_journal.py
  account_statement_import_paypal/models/account_statement_import.py
  account_statement_import_paypal/models/account_statement_import_paypal_mapping.py
  account_statement_import_paypal/models/account_statement_import_paypal_parser.py
  account_statement_import_paypal/readme/CONFIGURE.rst
  account_statement_import_paypal/readme/CONTRIBUTORS.rst
  account_statement_import_paypal/readme/DESCRIPTION.rst
  account_statement_import_paypal/readme/HISTORY.rst
  account_statement_import_paypal/readme/USAGE.rst
  account_statement_import_paypal/security/ir.model.access.csv
  account_statement_import_paypal/static/description/icon.png
  account_statement_import_paypal/static/description/index.html
  account_statement_import_paypal/tests/__init__.py
  account_statement_import_paypal/tests/fixtures/activity_en.csv
  account_statement_import_paypal/tests/fixtures/empty_activity.csv
  account_statement_import_paypal/tests/fixtures/statement_en.csv
  account_statement_import_paypal/tests/fixtures/statement_es.csv
  account_statement_import_paypal/tests/test_account_statement_import_paypal.py
  account_statement_import_paypal/views/account_statement_import.xml
  account_statement_import_paypal/views/account_statement_import_paypal_mapping.xml
  account_statement_import_paypal/wizards/__init__.py
  account_statement_import_paypal/wizards/account_statement_import_paypal_mapping_wizard.py
  account_statement_import_paypal/wizards/account_statement_import_paypal_mapping_wizard.xml
  setup/account_statement_import_paypal/odoo/addons/account_statement_import_paypal
  setup/account_statement_import_paypal/setup.py
Labels: bot is merging ⏳

#391 [14.0] [MIG] account_(bank_)statement_import_online(_ponto)
  account_statement_import_online/README.rst
  account_statement_import_online/__init__.py
  account_statement_import_online/__manifest__.py
  account_statement_import_online/data/account_statement_import_online.xml
  account_statement_import_online/i18n/account_statement_import_online.pot
  account_statement_import_online/i18n/nl.po
  account_statement_import_online/models/__init__.py
  account_statement_import_online/models/account_journal.py
  account_statement_import_online/models/online_bank_statement_provider.py
  account_statement_import_online/readme/CONFIGURE.rst
  account_statement_import_online/readme/CONTRIBUTORS.rst
  account_statement_import_online/readme/DESCRIPTION.rst
  account_statement_import_online/readme/USAGE.rst
  account_statement_import_online/security/ir.model.access.csv
  account_statement_import_online/security/online_bank_statement_provider.xml
  account_statement_import_online/static/description/icon.png
  account_statement_import_online/static/description/index.html
  account_statement_import_online/tests/__init__.py
  account_statement_import_online/tests/online_bank_statement_provider_dummy.py
  account_statement_import_online/tests/test_account_bank_statement_import_online.py
  account_statement_import_online/tests/test_account_journal.py
  account_statement_import_online/views/account_journal.xml
  account_statement_import_online/views/actions.xml
  account_statement_import_online/views/online_bank_statement_provider.xml
  account_statement_import_online/wizards/__init__.py
  account_statement_import_online/wizards/online_bank_statement_pull_wizard.py
  account_statement_import_online/wizards/online_bank_statement_pull_wizard.xml
  account_statement_import_online_ponto/README.rst
  account_statement_import_online_ponto/__init__.py
  account_statement_import_online_ponto/__manifest__.py
  account_statement_import_online_ponto/i18n/account_statement_import_online_ponto.pot
  account_statement_import_online_ponto/models/__init__.py
  account_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
  account_statement_import_online_ponto/readme/CONFIGURE.rst
  account_statement_import_online_ponto/readme/CONTRIBUTORS.rst
  account_statement_import_online_ponto/readme/DESCRIPTION.rst
  account_statement_import_online_ponto/readme/USAGE.rst
  account_statement_import_online_ponto/static/description/icon.png
  account_statement_import_online_ponto/static/description/index.html
  account_statement_import_online_ponto/tests/__init__.py
  account_statement_import_online_ponto/tests/test_account_statement_import_online_ponto.py
  account_statement_import_online_ponto/view/online_bank_statement_provider.xml
  oca_dependencies.txt
  setup/account_statement_import_online/odoo/addons/account_statement_import_online
  setup/account_statement_import_online/setup.py
  setup/account_statement_import_online_ponto/odoo/addons/account_statement_import_online_ponto
  setup/account_statement_import_online_ponto/setup.py
Labels: bot is merging ⏳

#386 [13.0][IMP] account_bank_statement_import_camt_oca: support DtTm
  account_bank_statement_import_camt_oca/models/parser.py
  account_bank_statement_import_camt_oca/test_files/test-camt053-bookgdt-dttm
  account_bank_statement_import_camt_oca/tests/test_import_bank_statement.py
Labels: approved, bot is merging ⏳, ready to merge

#205 [ADD] account_bank_statement_import_mt940_nl_mollie
  account_bank_statement_import_mt940_nl_mollie/README.rst
  account_bank_statement_import_mt940_nl_mollie/__init__.py
  account_bank_statement_import_mt940_nl_mollie/__manifest__.py
  account_bank_statement_import_mt940_nl_mollie/examples/Voorbeeld MT-940.mt940
  account_bank_statement_import_mt940_nl_mollie/models/__init__.py
  account_bank_statement_import_mt940_nl_mollie/models/account_bank_statement_import.py
  account_bank_statement_import_mt940_nl_mollie/readme/CONTRIBUTORS.rst
  account_bank_statement_import_mt940_nl_mollie/readme/CREDITS.rst
  account_bank_statement_import_mt940_nl_mollie/readme/DESCRIPTION.rst
  account_bank_statement_import_mt940_nl_mollie/static/description/icon.png
  account_bank_statement_import_mt940_nl_mollie/static/description/index.html
  account_bank_statement_import_mt940_nl_mollie/tests/__init__.py
  account_bank_statement_import_mt940_nl_mollie/tests/test_account_bank_statement_import_mt940_nl_mollie.py
  account_bank_statement_import_mt940_nl_mollie/views/account_bank_statement_import.xml
Labels: approved, bot is merging ⏳, needs review

#381 [13.0][FIX] absi- _camt_oca. Prevent recursion in exception handling
  account_bank_statement_import_camt_oca/models/account_bank_statement_import.py
Labels: bot is merging ⏳
