Repository OCA/bank-statement-import, pull requests merged in 2021-09, with the labels that each got.

#389 [13.0][MIG] account_bank_statement_import_online_transferwise
  account_bank_statement_import_online_transferwise/README.rst
  account_bank_statement_import_online_transferwise/__init__.py
  account_bank_statement_import_online_transferwise/__manifest__.py
  account_bank_statement_import_online_transferwise/i18n/account_bank_statement_import_online_transferwise.pot
  account_bank_statement_import_online_transferwise/i18n/nl.po
  account_bank_statement_import_online_transferwise/models/__init__.py
  account_bank_statement_import_online_transferwise/models/online_bank_statement_provider_transferwise.py
  account_bank_statement_import_online_transferwise/readme/CONFIGURE.rst
  account_bank_statement_import_online_transferwise/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_transferwise/readme/DESCRIPTION.rst
  account_bank_statement_import_online_transferwise/readme/USAGE.rst
  account_bank_statement_import_online_transferwise/static/description/icon.png
  account_bank_statement_import_online_transferwise/static/description/index.html
  account_bank_statement_import_online_transferwise/tests/__init__.py
  account_bank_statement_import_online_transferwise/tests/test_account_bank_statement_import_online_transferwise.py
  account_bank_statement_import_online_transferwise/views/online_bank_statement_provider.xml
  setup/account_bank_statement_import_online_transferwise/odoo/addons/account_bank_statement_import_online_transferwise
  setup/account_bank_statement_import_online_transferwise/setup.py
Labels: bot is merging ⏳

#415 [13.0][MIG] account_bank_statement_import_online_paypal
  account_bank_statement_import_online_paypal/README.rst
  account_bank_statement_import_online_paypal/__init__.py
  account_bank_statement_import_online_paypal/__manifest__.py
  account_bank_statement_import_online_paypal/i18n/account_bank_statement_import_online_paypal.pot
  account_bank_statement_import_online_paypal/models/__init__.py
  account_bank_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
  account_bank_statement_import_online_paypal/readme/CONFIGURE.rst
  account_bank_statement_import_online_paypal/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_paypal/readme/DESCRIPTION.rst
  account_bank_statement_import_online_paypal/readme/ROADMAP.rst
  account_bank_statement_import_online_paypal/readme/USAGE.rst
  account_bank_statement_import_online_paypal/static/description/icon.png
  account_bank_statement_import_online_paypal/static/description/index.html
  account_bank_statement_import_online_paypal/tests/__init__.py
  account_bank_statement_import_online_paypal/tests/test_account_bank_statement_import_online_paypal.py
  account_bank_statement_import_online_paypal/views/online_bank_statement_provider.xml
  setup/account_bank_statement_import_online_paypal/odoo/addons/account_bank_statement_import_online_paypal
  setup/account_bank_statement_import_online_paypal/setup.py
Labels: bot is merging ⏳

#419 [FIX] account_statement_import_online_ponto: verify TLS
  account_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
Labels: approved

#420 [13.0][FIX] account_statement_import_online_ponto: verify TLS
  account_bank_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
Labels: approved, bot is merging ⏳
