Repository OCA/bank-statement-import, pull requests merged in 2021-06, with the labels that each got.

#392 [14][account_statement_import][FIX] Error string formatting
  account_statement_import/wizard/account_statement_import.py
Labels: bot is merging ⏳

#78 8.0 enhanced balance determination
  .travis.yml
  account_bank_statement_import/tests/test_import_file.py
  account_bank_statement_import_camt/models/parser.py
Labels: approved, bot is merging ⏳, ready to merge

#395 [FIX] account_bank_statement_import_txt_xlsx: Translation issue
  account_bank_statement_import_txt_xlsx/i18n/pt.po
Labels: approved, ready to merge
