Repository OCA/bank-statement-import, pull requests merged in 2022-04, with the labels that each got.

#445 [13.0][FIX] account_bank_statement_import_online: Default value for active field
  account_bank_statement_import_online/models/account_journal.py
Labels: bot is merging ⏳

#459 [13.0][MIG] account_bank_statement_import_online_qonto: Migration to 13.0
  account_bank_statement_import_online_qonto/README.rst
  account_bank_statement_import_online_qonto/__init__.py
  account_bank_statement_import_online_qonto/__manifest__.py
  account_bank_statement_import_online_qonto/i18n/account_bank_statement_import_online_qonto.pot
  account_bank_statement_import_online_qonto/models/__init__.py
  account_bank_statement_import_online_qonto/models/online_bank_statement_provider_qonto.py
  account_bank_statement_import_online_qonto/readme/CONFIGURE.rst
  account_bank_statement_import_online_qonto/readme/CONTRIBUTORS.rst
  account_bank_statement_import_online_qonto/readme/DESCRIPTION.rst
  account_bank_statement_import_online_qonto/readme/USAGE.rst
  account_bank_statement_import_online_qonto/static/description/icon.png
  account_bank_statement_import_online_qonto/static/description/index.html
  account_bank_statement_import_online_qonto/tests/__init__.py
  account_bank_statement_import_online_qonto/tests/test_account_bank_statement_import_online_qonto.py
  account_bank_statement_import_online_qonto/view/online_bank_statement_provider.xml
  setup/account_bank_statement_import_online_qonto/odoo/addons/account_bank_statement_import_online_qonto
  setup/account_bank_statement_import_online_qonto/setup.py
Labels: approved, bot is merging ⏳

#460 [IMP] account_statement_import_camt: look for currency under Ntry
  account_statement_import_camt/models/parser.py
  account_statement_import_camt/readme/CONTRIBUTORS.rst
  account_statement_import_camt/test_files/golden-camt054.pydata
  account_statement_import_camt/test_files/test-camt054
  account_statement_import_camt/tests/test_import_bank_statement.py
Labels: approved, ready to merge, bot is merging ⏳

#464 [FIX] Change demo data
  account_statement_import/demo/partner_bank.xml
Labels: approved, bot is merging ⏳
