Repository OCA/bank-statement-import, pull requests merged in 2022-06, with the labels that each got.

#471 [FIX] *_paypal: correct imports
  account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_parser.py
Labels: approved, bot is merging ⏳

#432 [14.0] [ADD] account statement import online ing
  account_statement_import_online_ponto_ing/README.rst
  account_statement_import_online_ponto_ing/__init__.py
  account_statement_import_online_ponto_ing/__manifest__.py
  account_statement_import_online_ponto_ing/models/__init__.py
  account_statement_import_online_ponto_ing/models/online_bank_statement_provider_ponto.py
  account_statement_import_online_ponto_ing/readme/CONFIGURE.rst
  account_statement_import_online_ponto_ing/readme/CONTRIBUTORS.rst
  account_statement_import_online_ponto_ing/readme/DESCRIPTION.rst
  account_statement_import_online_ponto_ing/static/description/icon.png
  account_statement_import_online_ponto_ing/static/description/index.html
  account_statement_import_online_ponto_ing/tests/__init__.py
  account_statement_import_online_ponto_ing/tests/test_account_statement_import_online_ponto.py
  setup/account_statement_import_online_ponto_ing/odoo/addons/account_statement_import_online_ponto_ing
  setup/account_statement_import_online_ponto_ing/setup.py
Labels: approved, bot is merging ⏳

#416 [13.0][MIG] account_bank_statement_import_split
  account_bank_statement_import_split/README.rst
  account_bank_statement_import_split/__init__.py
  account_bank_statement_import_split/__manifest__.py
  account_bank_statement_import_split/i18n/account_bank_statement_import_split.pot
  account_bank_statement_import_split/models/__init__.py
  account_bank_statement_import_split/models/account_bank_statement_import.py
  account_bank_statement_import_split/readme/CONTRIBUTORS.rst
  account_bank_statement_import_split/readme/DESCRIPTION.rst
  account_bank_statement_import_split/static/description/icon.png
  account_bank_statement_import_split/static/description/index.html
  account_bank_statement_import_split/tests/__init__.py
  account_bank_statement_import_split/tests/test_account_bank_statement_import_split.py
  account_bank_statement_import_split/views/account_bank_statement_import.xml
  setup/account_bank_statement_import_split/odoo/addons/account_bank_statement_import_split
  setup/account_bank_statement_import_split/setup.py
Labels: bot is merging ⏳

#461 [12.0][FIX] *_ponto: solve exception on empty name
  account_bank_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
Labels: bot is merging ⏳

#438 [14.0][IMP] account_bank_statement_import_camt : More verbose narration (notes)
  account_statement_import_camt/models/parser.py
  account_statement_import_camt/readme/newsfragment/1_verbose_narration.feature
  account_statement_import_camt/test_files/golden-camt053-txdtls.pydata
  account_statement_import_camt/test_files/golden-camt053.pydata
  account_statement_import_camt/test_files/golden-camt054.pydata
Labels: approved, ready to merge, bot is merging ⏳
