Repository OCA/bank-statement-import, pull requests merged in 2022-05, with the labels that each got.

#463 [15.0][MIG]account_statement_import_online_ponto
  account_statement_import_online_ponto/README.rst
  account_statement_import_online_ponto/__init__.py
  account_statement_import_online_ponto/__manifest__.py
  account_statement_import_online_ponto/i18n/account_statement_import_online_ponto.pot
  account_statement_import_online_ponto/i18n/ca.po
  account_statement_import_online_ponto/i18n/it.po
  account_statement_import_online_ponto/models/__init__.py
  account_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
  account_statement_import_online_ponto/readme/CONFIGURE.rst
  account_statement_import_online_ponto/readme/CONTRIBUTORS.rst
  account_statement_import_online_ponto/readme/DESCRIPTION.rst
  account_statement_import_online_ponto/readme/USAGE.rst
  account_statement_import_online_ponto/static/description/icon.png
  account_statement_import_online_ponto/static/description/index.html
  account_statement_import_online_ponto/tests/__init__.py
  account_statement_import_online_ponto/tests/test_account_statement_import_online_ponto.py
  account_statement_import_online_ponto/view/online_bank_statement_provider.xml
  setup/account_statement_import_online_ponto/odoo/addons/account_statement_import_online_ponto
  setup/account_statement_import_online_ponto/setup.py
Labels: bot is merging ⏳

#468 [FIX] account_bank_statement_import_paypal don't declare standard python
  account_bank_statement_import_paypal/__manifest__.py
Labels: approved, bot is merging ⏳

#465 [14.0][MIG] account_bank_statement_import_move_line > account_statement_import_move_line
  account_statement_import_move_line/README.rst
  account_statement_import_move_line/__init__.py
  account_statement_import_move_line/__manifest__.py
  account_statement_import_move_line/i18n/account_bank_statement_import_move_line.pot
  account_statement_import_move_line/i18n/de.po
  account_statement_import_move_line/i18n/es.po
  account_statement_import_move_line/i18n/fr.po
  account_statement_import_move_line/i18n/hr.po
  account_statement_import_move_line/i18n/nl.po
  account_statement_import_move_line/i18n/pt_BR.po
  account_statement_import_move_line/i18n/pt_PT.po
  account_statement_import_move_line/i18n/sl.po
  account_statement_import_move_line/models/__init__.py
  account_statement_import_move_line/models/account_move_line.py
  account_statement_import_move_line/readme/CONFIGURE.rst
  account_statement_import_move_line/readme/CONTRIBUTORS.rst
  account_statement_import_move_line/readme/DESCRIPTION.rst
  account_statement_import_move_line/readme/USAGE.rst
  account_statement_import_move_line/security/ir.model.access.csv
  account_statement_import_move_line/static/description/icon.png
  account_statement_import_move_line/static/description/index.html
  account_statement_import_move_line/tests/__init__.py
  account_statement_import_move_line/tests/test_account_bank_statement_import_move_line.py
  account_statement_import_move_line/views/account_bank_statement_view.xml
  account_statement_import_move_line/wizards/__init__.py
  account_statement_import_move_line/wizards/account_statement_line_create.py
  account_statement_import_move_line/wizards/account_statement_line_create_view.xml
  setup/account_statement_import_move_line/odoo/addons/account_statement_import_move_line
  setup/account_statement_import_move_line/setup.py
Labels: approved, bot is merging ⏳

#452 [14.0][MIG] account_statement_import_online_paypal
  account_statement_import_online_paypal/README.rst
  account_statement_import_online_paypal/__init__.py
  account_statement_import_online_paypal/__manifest__.py
  account_statement_import_online_paypal/i18n/account_statement_import_online_paypal.pot
  account_statement_import_online_paypal/models/__init__.py
  account_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
  account_statement_import_online_paypal/readme/CONFIGURE.rst
  account_statement_import_online_paypal/readme/CONTRIBUTORS.rst
  account_statement_import_online_paypal/readme/DESCRIPTION.rst
  account_statement_import_online_paypal/readme/ROADMAP.rst
  account_statement_import_online_paypal/readme/USAGE.rst
  account_statement_import_online_paypal/static/description/icon.png
  account_statement_import_online_paypal/static/description/index.html
  account_statement_import_online_paypal/tests/__init__.py
  account_statement_import_online_paypal/tests/test_account_statement_import_online_paypal.py
  account_statement_import_online_paypal/views/online_bank_statement_provider.xml
  setup/account_statement_import_online_paypal/odoo/addons/account_statement_import_online_paypal
  setup/account_statement_import_online_paypal/setup.py
Labels: approved, ready to merge, bot is merging ⏳
