Repository OCA/bank-statement-import, pull requests merged in 2023-03, with the labels that each got.

#514 [15.0][MIG] account_statement_import_ofx
  account_statement_import_ofx/README.rst
  account_statement_import_ofx/__init__.py
  account_statement_import_ofx/__manifest__.py
  account_statement_import_ofx/i18n/account_bank_statement_import_ofx.pot
  account_statement_import_ofx/i18n/account_statement_import_ofx.pot
  account_statement_import_ofx/i18n/de.po
  account_statement_import_ofx/i18n/es.po
  account_statement_import_ofx/i18n/es_AR.po
  account_statement_import_ofx/i18n/fi.po
  account_statement_import_ofx/i18n/fr.po
  account_statement_import_ofx/i18n/fr_CH.po
  account_statement_import_ofx/i18n/fr_FR.po
  account_statement_import_ofx/i18n/gl.po
  account_statement_import_ofx/i18n/it.po
  account_statement_import_ofx/i18n/lt_LT.po
  account_statement_import_ofx/i18n/nb_NO.po
  account_statement_import_ofx/i18n/nl.po
  account_statement_import_ofx/i18n/pt_BR.po
  account_statement_import_ofx/i18n/pt_PT.po
  account_statement_import_ofx/i18n/sl.po
  account_statement_import_ofx/models/__init__.py
  account_statement_import_ofx/models/account_journal.py
  account_statement_import_ofx/readme/CONTRIBUTORS.rst
  account_statement_import_ofx/readme/DESCRIPTION.rst
  account_statement_import_ofx/readme/INSTALL.rst
  account_statement_import_ofx/static/description/icon.png
  account_statement_import_ofx/static/description/index.html
  account_statement_import_ofx/tests/__init__.py
  account_statement_import_ofx/tests/test_import_bank_statement.py
  account_statement_import_ofx/tests/test_ofx_file/test_ofx.ofx
  account_statement_import_ofx/tests/test_ofx_file/test_ofx_iban.ofx
  account_statement_import_ofx/tests/test_ofx_file/test_ofx_wrong.ofx
  account_statement_import_ofx/views/account_statement_import.xml
  account_statement_import_ofx/wizard/__init__.py
  account_statement_import_ofx/wizard/account_statement_import.py
  requirements.txt
  setup/account_statement_import_ofx/odoo/addons/account_statement_import_ofx
  setup/account_statement_import_ofx/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#572 [15.0][MIG] account_bank_statement_import_move_line: Migration to version 15.0
  account_bank_statement_import_move_line/README.rst
  account_bank_statement_import_move_line/__init__.py
  account_bank_statement_import_move_line/__manifest__.py
  account_bank_statement_import_move_line/i18n/account_bank_statement_import_move_line.pot
  account_bank_statement_import_move_line/i18n/de.po
  account_bank_statement_import_move_line/i18n/es.po
  account_bank_statement_import_move_line/i18n/fr.po
  account_bank_statement_import_move_line/i18n/hr.po
  account_bank_statement_import_move_line/i18n/nl.po
  account_bank_statement_import_move_line/i18n/pt_BR.po
  account_bank_statement_import_move_line/i18n/pt_PT.po
  account_bank_statement_import_move_line/i18n/sl.po
  account_bank_statement_import_move_line/models/__init__.py
  account_bank_statement_import_move_line/models/account_move_line.py
  account_bank_statement_import_move_line/readme/CONFIGURE.rst
  account_bank_statement_import_move_line/readme/CONTRIBUTORS.rst
  account_bank_statement_import_move_line/readme/DESCRIPTION.rst
  account_bank_statement_import_move_line/readme/USAGE.rst
  account_bank_statement_import_move_line/security/ir.model.access.csv
  account_bank_statement_import_move_line/static/description/icon.png
  account_bank_statement_import_move_line/static/description/index.html
  account_bank_statement_import_move_line/tests/__init__.py
  account_bank_statement_import_move_line/tests/test_account_bank_statement_import_move_line.py
  account_bank_statement_import_move_line/views/account_bank_statement_view.xml
  account_bank_statement_import_move_line/wizards/__init__.py
  account_bank_statement_import_move_line/wizards/account_statement_line_create.py
  account_bank_statement_import_move_line/wizards/account_statement_line_create_view.xml
  setup/account_bank_statement_import_move_line/odoo/addons/account_bank_statement_import_move_line
  setup/account_bank_statement_import_move_line/setup.py
Labels: approved, bot is merging ⏳

#577 [16.0][MIG] account_statement_import_ofx
  account_statement_import_ofx/README.rst
  account_statement_import_ofx/__init__.py
  account_statement_import_ofx/__manifest__.py
  account_statement_import_ofx/i18n/account_bank_statement_import_ofx.pot
  account_statement_import_ofx/i18n/account_statement_import_ofx.pot
  account_statement_import_ofx/i18n/de.po
  account_statement_import_ofx/i18n/es.po
  account_statement_import_ofx/i18n/es_AR.po
  account_statement_import_ofx/i18n/fi.po
  account_statement_import_ofx/i18n/fr.po
  account_statement_import_ofx/i18n/fr_CH.po
  account_statement_import_ofx/i18n/fr_FR.po
  account_statement_import_ofx/i18n/gl.po
  account_statement_import_ofx/i18n/it.po
  account_statement_import_ofx/i18n/lt_LT.po
  account_statement_import_ofx/i18n/nb_NO.po
  account_statement_import_ofx/i18n/nl.po
  account_statement_import_ofx/i18n/pt_BR.po
  account_statement_import_ofx/i18n/pt_PT.po
  account_statement_import_ofx/i18n/sl.po
  account_statement_import_ofx/models/__init__.py
  account_statement_import_ofx/models/account_journal.py
  account_statement_import_ofx/readme/CONTRIBUTORS.rst
  account_statement_import_ofx/readme/DESCRIPTION.rst
  account_statement_import_ofx/readme/INSTALL.rst
  account_statement_import_ofx/static/description/icon.png
  account_statement_import_ofx/static/description/index.html
  account_statement_import_ofx/tests/__init__.py
  account_statement_import_ofx/tests/test_import_bank_statement.py
  account_statement_import_ofx/tests/test_ofx_file/test_ofx.ofx
  account_statement_import_ofx/tests/test_ofx_file/test_ofx_iban.ofx
  account_statement_import_ofx/tests/test_ofx_file/test_ofx_wrong.ofx
  account_statement_import_ofx/views/account_statement_import.xml
  account_statement_import_ofx/wizard/__init__.py
  account_statement_import_ofx/wizard/account_statement_import.py
  requirements.txt
  setup/account_statement_import_ofx/odoo/addons/account_statement_import_ofx
  setup/account_statement_import_ofx/setup.py
Labels: bot is merging ⏳
