Repository OCA/bank-statement-import, pull requests merged in 2023-02, with the labels that each got.

#542 [14.0] [FIX] ponto import
  account_statement_import_online_ponto/__manifest__.py
  account_statement_import_online_ponto/models/__init__.py
  account_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
  account_statement_import_online_ponto/models/ponto_interface.py
  account_statement_import_online_ponto/readme/CONTRIBUTORS.rst
  account_statement_import_online_ponto/tests/__init__.py
  account_statement_import_online_ponto/tests/test_account_statement_import_online_ponto.py
  account_statement_import_online_ponto/tests/test_ponto_interface.py
  account_statement_import_online_ponto/views/online_bank_statement_provider.xml
  account_statement_import_online_ponto_ing/tests/__init__.py
  account_statement_import_online_ponto_ing/tests/test_account_statement_import_online_ponto.py
Labels: approved, ready to merge, bot is merging ⏳

#536 [IMP] account_bank_statement_import_txt_xlsx: Allow mapping with reference to column numbers, and concatenation
  account_bank_statement_import_txt_xlsx/__manifest__.py
  account_bank_statement_import_txt_xlsx/models/account_bank_statement_import.py
  account_bank_statement_import_txt_xlsx/models/account_bank_statement_import_sheet_mapping.py
  account_bank_statement_import_txt_xlsx/models/account_bank_statement_import_sheet_parser.py
  account_bank_statement_import_txt_xlsx/tests/fixtures/original_currency_no_header.csv
  account_bank_statement_import_txt_xlsx/tests/test_account_bank_statement_import_txt_xlsx.py
  account_bank_statement_import_txt_xlsx/views/account_bank_statement_import_sheet_mapping.xml
  requirements.txt
Labels: bot is merging ⏳

#533 [15.0]account_statement_import - set correct company_id on ir_attachment
  account_statement_import/wizard/account_statement_import.py
Labels: approved, bot is merging ⏳

#568 [14.0][IMP] account_statement_import_txt_xlsx: forward port commits
  account_statement_import_online/__manifest__.py
  account_statement_import_txt_xlsx/__manifest__.py
  account_statement_import_txt_xlsx/models/account_statement_import.py
  account_statement_import_txt_xlsx/models/account_statement_import_sheet_mapping.py
  account_statement_import_txt_xlsx/models/account_statement_import_sheet_parser.py
  account_statement_import_txt_xlsx/tests/fixtures/original_currency_no_header.csv
  account_statement_import_txt_xlsx/tests/test_account_statement_import_txt_xlsx.py
  account_statement_import_txt_xlsx/views/account_statement_import_sheet_mapping.xml
  requirements.txt
  test-requirements.txt
Labels: bot is merging ⏳

#569 [15.0][IMP] account_bank_statement_import_txt_xlsx: several forward ports
  account_statement_import_online/__manifest__.py
  account_statement_import_txt_xlsx/__manifest__.py
  account_statement_import_txt_xlsx/migrations/14.0.1.0.0/pre-migrate.py
  account_statement_import_txt_xlsx/migrations/15.0.1.1.0/pre-migrate.py
  account_statement_import_txt_xlsx/models/account_statement_import.py
  account_statement_import_txt_xlsx/models/account_statement_import_sheet_mapping.py
  account_statement_import_txt_xlsx/models/account_statement_import_sheet_parser.py
  account_statement_import_txt_xlsx/tests/fixtures/debit_credit_amount.csv
  account_statement_import_txt_xlsx/tests/fixtures/original_currency_no_header.csv
  account_statement_import_txt_xlsx/tests/test_account_statement_import_txt_xlsx.py
  account_statement_import_txt_xlsx/views/account_statement_import_sheet_mapping.xml
  account_statement_import_txt_xlsx/wizards/account_statement_import_sheet_mapping_wizard.py
  account_statement_import_txt_xlsx/wizards/account_statement_import_sheet_mapping_wizard.xml
  requirements.txt
  test-requirements.txt
Labels: bot is merging ⏳

#570 [15.0][MIG] account_statement_import_base
  account_statement_import/__manifest__.py
  account_statement_import/models/__init__.py
  account_statement_import/views/account_bank_statement_line.xml
  account_statement_import/wizard/account_statement_import.py
  account_statement_import/wizard/account_statement_import_view.xml
  account_statement_import_base/README.rst
  account_statement_import_base/__init__.py
  account_statement_import_base/__manifest__.py
  account_statement_import_base/i18n/account_statement_import_base.pot
  account_statement_import_base/models/__init__.py
  account_statement_import_base/models/account_bank_statement_line.py
  account_statement_import_base/models/account_journal.py
  account_statement_import_base/readme/CONTRIBUTORS.rst
  account_statement_import_base/readme/DESCRIPTION.rst
  account_statement_import_base/static/description/icon.png
  account_statement_import_base/static/description/index.html
  account_statement_import_base/views/account_bank_statement_line.xml
  account_statement_import_online/__manifest__.py
  account_statement_import_online/migrations/15.0.3.0.0/post-migration.py
  account_statement_import_online/migrations/15.0.3.0.0/pre-migration.py
  account_statement_import_online/models/__init__.py
  account_statement_import_online/models/account_bank_statement_line.py
  account_statement_import_online/models/online_bank_statement_provider.py
  account_statement_import_online/views/account_bank_statement_line.xml
  account_statement_import_online/views/account_journal.xml
  account_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
  setup/account_statement_import_base/odoo/addons/account_statement_import_base
  setup/account_statement_import_base/setup.py
Labels: bot is merging ⏳

#534 [15.0][MIG] port pr522, 527 from 14.0 to 15.0
  account_statement_import/__manifest__.py
  account_statement_import/static/src/js/account_dashboard_kanban.js
  account_statement_import/static/src/xml/account_dashboard_kanban.xml
  account_statement_import/views/account_journal.xml
  account_statement_import/wizard/account_statement_import.py
  account_statement_import/wizard/account_statement_import_view.xml
Labels: bot is merging ⏳

#573 [15.0][FIX] account_statement_import_txt_xlsx: Don't try to parse if no mapping
  account_statement_import_txt_xlsx/models/account_statement_import.py
Labels: bot is merging ⏳

#574 [15.0][FIX] account_statement_import_paypal: Don't do anything if no mapping
  account_statement_import_paypal/models/account_statement_import.py
Labels: bot is merging ⏳
