Repository OCA/bank-statement-import, pull requests merged in 2023-04, with the labels that each got.

#581 [13.0][FIX] account_bank_statement_import_txt_xlsx: only consider parsing when a mapping sheet is specified
  account_bank_statement_import_txt_xlsx/models/account_bank_statement_import.py
Labels: approved, bot is merging ⏳

#582 [14.0][FIX] account_statement_import_txt_xlsx: only consider parsing when a mapping sheet is specified (forward port)
  account_statement_import_txt_xlsx/models/account_statement_import.py
Labels: bot is merging ⏳

#583 [13.0][FIX] account_bank_statement_import_paypal: parse only if mapping if specified
  account_bank_statement_import_paypal/models/account_bank_statement_import.py
Labels: bot is merging ⏳

#584 [14.0][FIX] account_statement_import_paypal: parse only if mapping if specified (forward port)
  account_statement_import_paypal/models/account_statement_import.py
Labels: bot is merging ⏳

#560 [14.0] account_statement_import_camt - fix counterparty data
  account_statement_import_camt/models/parser.py
  account_statement_import_camt/test_files/golden-camt053-txdtls.pydata
  account_statement_import_camt/test_files/golden-camt053.pydata
  account_statement_import_camt/test_files/golden-camt054.pydata
Labels: approved, bot is merging ⏳

#585 account_statement_import_camt - fix counterparty data
  account_statement_import_camt/models/parser.py
Labels: bot is merging ⏳

#571 [15.0][MIG] account_statement_import_online_paypal
  account_statement_import_online_paypal/README.rst
  account_statement_import_online_paypal/__init__.py
  account_statement_import_online_paypal/__manifest__.py
  account_statement_import_online_paypal/i18n/account_statement_import_online_paypal.pot
  account_statement_import_online_paypal/models/__init__.py
  account_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
  account_statement_import_online_paypal/readme/CONFIGURE.rst
  account_statement_import_online_paypal/readme/CONTRIBUTORS.rst
  account_statement_import_online_paypal/readme/DESCRIPTION.rst
  account_statement_import_online_paypal/readme/ROADMAP.rst
  account_statement_import_online_paypal/readme/USAGE.rst
  account_statement_import_online_paypal/static/description/icon.png
  account_statement_import_online_paypal/static/description/index.html
  account_statement_import_online_paypal/tests/__init__.py
  account_statement_import_online_paypal/tests/test_account_statement_import_online_paypal.py
  account_statement_import_online_paypal/views/online_bank_statement_provider.xml
  setup/account_statement_import_online_paypal/odoo/addons/account_statement_import_online_paypal
  setup/account_statement_import_online_paypal/setup.py
Labels: approved, ready to merge, bot is merging ⏳
