Repository OCA/bank-statement-import, pull requests merged in 2023-10, with the labels that each got.

#599 [FIX] account_statement_import: Ensure the load of the view
  account_statement_import/static/src/js/account_dashboard_kanban.js
Labels: bot is merging ⏳, stale

#548 [16.0][MIG] account_statement_import_online: Migration to 16.0
  .pre-commit-config.yaml
  account_statement_import_online/README.rst
  account_statement_import_online/__init__.py
  account_statement_import_online/__manifest__.py
  account_statement_import_online/data/account_statement_import_online.xml
  account_statement_import_online/i18n/account_statement_import_online.pot
  account_statement_import_online/i18n/it.po
  account_statement_import_online/i18n/nl.po
  account_statement_import_online/models/__init__.py
  account_statement_import_online/models/account_journal.py
  account_statement_import_online/models/online_bank_statement_provider.py
  account_statement_import_online/readme/CONFIGURE.rst
  account_statement_import_online/readme/CONTRIBUTORS.rst
  account_statement_import_online/readme/DESCRIPTION.rst
  account_statement_import_online/readme/USAGE.rst
  account_statement_import_online/security/ir.model.access.csv
  account_statement_import_online/security/online_bank_statement_provider.xml
  account_statement_import_online/static/description/icon.png
  account_statement_import_online/static/description/index.html
  account_statement_import_online/tests/__init__.py
  account_statement_import_online/tests/online_bank_statement_provider_dummy.py
  account_statement_import_online/tests/test_account_bank_statement_import_online.py
  account_statement_import_online/views/account_journal.xml
  account_statement_import_online/views/actions.xml
  account_statement_import_online/views/online_bank_statement_provider.xml
  account_statement_import_online/wizards/__init__.py
  account_statement_import_online/wizards/online_bank_statement_pull_wizard.py
  account_statement_import_online/wizards/online_bank_statement_pull_wizard.xml
  setup/account_statement_import_online/odoo/addons/account_statement_import_online
  setup/account_statement_import_online/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#554 [16.0][MIG] account_statement_import_online_ponto: Migration to 16.0
  account_statement_import_online/models/account_journal.py
  account_statement_import_online_ponto/README.rst
  account_statement_import_online_ponto/__init__.py
  account_statement_import_online_ponto/__manifest__.py
  account_statement_import_online_ponto/i18n/account_statement_import_online_ponto.pot
  account_statement_import_online_ponto/i18n/ca.po
  account_statement_import_online_ponto/i18n/it.po
  account_statement_import_online_ponto/models/__init__.py
  account_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
  account_statement_import_online_ponto/models/ponto_interface.py
  account_statement_import_online_ponto/readme/CONFIGURE.rst
  account_statement_import_online_ponto/readme/CONTRIBUTORS.rst
  account_statement_import_online_ponto/readme/DESCRIPTION.rst
  account_statement_import_online_ponto/readme/USAGE.rst
  account_statement_import_online_ponto/static/description/icon.png
  account_statement_import_online_ponto/static/description/index.html
  account_statement_import_online_ponto/tests/__init__.py
  account_statement_import_online_ponto/tests/test_account_statement_import_online_ponto.py
  account_statement_import_online_ponto/tests/test_ponto_interface.py
  account_statement_import_online_ponto/views/online_bank_statement_provider.xml
  setup/account_statement_import_online_ponto/odoo/addons/account_statement_import_online_ponto
  setup/account_statement_import_online_ponto/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#630 [16.0][MIG] account_statement_import_online_paypal: Migration to version 16.0
  account_statement_import_online_paypal/README.rst
  account_statement_import_online_paypal/__init__.py
  account_statement_import_online_paypal/__manifest__.py
  account_statement_import_online_paypal/i18n/account_statement_import_online_paypal.pot
  account_statement_import_online_paypal/models/__init__.py
  account_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
  account_statement_import_online_paypal/readme/CONFIGURE.rst
  account_statement_import_online_paypal/readme/CONTRIBUTORS.rst
  account_statement_import_online_paypal/readme/DESCRIPTION.rst
  account_statement_import_online_paypal/readme/ROADMAP.rst
  account_statement_import_online_paypal/readme/USAGE.rst
  account_statement_import_online_paypal/static/description/icon.png
  account_statement_import_online_paypal/static/description/index.html
  account_statement_import_online_paypal/tests/__init__.py
  account_statement_import_online_paypal/tests/test_account_statement_import_online_paypal.py
  account_statement_import_online_paypal/views/online_bank_statement_provider.xml
  setup/account_statement_import_online_paypal/odoo/addons/account_statement_import_online_paypal
  setup/account_statement_import_online_paypal/setup.py
Labels: approved, bot is merging ⏳

#634 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_statement_import_online/i18n/account_statement_import_online.pot
  account_statement_import_online_ponto/i18n/account_statement_import_online_ponto.pot
  account_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
Labels: help wanted, needs review, bot is merging ⏳

#628 [16.0][MIG] account_statement_import_txt_xlsx > account_statement_import_sheet_file: Migration to 16.0
  account_statement_import_sheet_file/README.rst
  account_statement_import_sheet_file/__init__.py
  account_statement_import_sheet_file/__manifest__.py
  account_statement_import_sheet_file/data/map_data.xml
  account_statement_import_sheet_file/i18n/account_statement_import_sheet_file.pot
  account_statement_import_sheet_file/i18n/es.po
  account_statement_import_sheet_file/i18n/es_AR.po
  account_statement_import_sheet_file/i18n/it.po
  account_statement_import_sheet_file/i18n/nl.po
  account_statement_import_sheet_file/i18n/pt.po
  account_statement_import_sheet_file/i18n/zh_CN.po
  account_statement_import_sheet_file/migrations/16.0.1.0.0/pre-migration.py
  account_statement_import_sheet_file/models/__init__.py
  account_statement_import_sheet_file/models/account_journal.py
  account_statement_import_sheet_file/models/account_statement_import.py
  account_statement_import_sheet_file/models/account_statement_import_sheet_mapping.py
  account_statement_import_sheet_file/models/account_statement_import_sheet_parser.py
  account_statement_import_sheet_file/readme/CONFIGURE.rst
  account_statement_import_sheet_file/readme/CONTRIBUTORS.rst
  account_statement_import_sheet_file/readme/DESCRIPTION.rst
  account_statement_import_sheet_file/readme/HISTORY.rst
  account_statement_import_sheet_file/readme/USAGE.rst
  account_statement_import_sheet_file/security/ir.model.access.csv
  account_statement_import_sheet_file/static/description/icon.png
  account_statement_import_sheet_file/static/description/index.html
  account_statement_import_sheet_file/tests/__init__.py
  account_statement_import_sheet_file/tests/fixtures/balance.csv
  account_statement_import_sheet_file/tests/fixtures/debit_credit.csv
  account_statement_import_sheet_file/tests/fixtures/debit_credit_amount.csv
  account_statement_import_sheet_file/tests/fixtures/empty_statement_en.csv
  account_statement_import_sheet_file/tests/fixtures/empty_statement_en.xlsx
  account_statement_import_sheet_file/tests/fixtures/meta_data_separated_credit_debit.csv
  account_statement_import_sheet_file/tests/fixtures/meta_data_separated_credit_debit.xlsx
  account_statement_import_sheet_file/tests/fixtures/multi_currency.csv
  account_statement_import_sheet_file/tests/fixtures/original_currency.csv
  account_statement_import_sheet_file/tests/fixtures/original_currency_empty.csv
  account_statement_import_sheet_file/tests/fixtures/original_currency_no_header.csv
  account_statement_import_sheet_file/tests/fixtures/sample_statement_en.csv
  account_statement_import_sheet_file/tests/fixtures/sample_statement_en.xlsx
  account_statement_import_sheet_file/tests/test_account_statement_import_sheet_file.py
  account_statement_import_sheet_file/views/account_journal_views.xml
  account_statement_import_sheet_file/views/account_statement_import.xml
  account_statement_import_sheet_file/views/account_statement_import_sheet_mapping.xml
  requirements.txt
  setup/account_statement_import_sheet_file/odoo/addons/account_statement_import_sheet_file
  setup/account_statement_import_sheet_file/setup.py
Labels: approved, bot is merging ⏳
