Repository OCA/bank-statement-import, pull requests merged in 2023-07, with the labels that each got.

#556 [16.0] [MIG] account_statement_import_camt: Migrate to version 16.0
  account_statement_import_camt/README.rst
  account_statement_import_camt/__init__.py
  account_statement_import_camt/__manifest__.py
  account_statement_import_camt/i18n/account_statement_import_camt.pot
  account_statement_import_camt/i18n/de.po
  account_statement_import_camt/i18n/es.po
  account_statement_import_camt/i18n/fa.po
  account_statement_import_camt/i18n/fi.po
  account_statement_import_camt/i18n/fr.po
  account_statement_import_camt/i18n/fr_CH.po
  account_statement_import_camt/i18n/gl.po
  account_statement_import_camt/i18n/hr.po
  account_statement_import_camt/i18n/it.po
  account_statement_import_camt/i18n/lt_LT.po
  account_statement_import_camt/i18n/nb_NO.po
  account_statement_import_camt/i18n/nl.po
  account_statement_import_camt/i18n/pt_BR.po
  account_statement_import_camt/i18n/pt_PT.po
  account_statement_import_camt/i18n/sl.po
  account_statement_import_camt/models/__init__.py
  account_statement_import_camt/models/account_bank_statement_line.py
  account_statement_import_camt/models/account_journal.py
  account_statement_import_camt/models/account_statement_import.py
  account_statement_import_camt/models/bank_statement.py
  account_statement_import_camt/models/parser.py
  account_statement_import_camt/readme/CONTRIBUTORS.rst
  account_statement_import_camt/readme/CREDITS.rst
  account_statement_import_camt/readme/DESCRIPTION.rst
  account_statement_import_camt/readme/newsfragment/1_verbose_narration.feature
  account_statement_import_camt/static/description/icon.png
  account_statement_import_camt/static/description/index.html
  account_statement_import_camt/test_files/golden-camt053-no-ntry.pydata
  account_statement_import_camt/test_files/golden-camt053-txdtls.pydata
  account_statement_import_camt/test_files/golden-camt053.pydata
  account_statement_import_camt/test_files/golden-camt054.pydata
  account_statement_import_camt/test_files/test-camt053
  account_statement_import_camt/test_files/test-camt053-no-ntry
  account_statement_import_camt/test_files/test-camt053-txdtls
  account_statement_import_camt/test_files/test-camt053.zip
  account_statement_import_camt/test_files/test-camt054
  account_statement_import_camt/tests/__init__.py
  account_statement_import_camt/tests/test_import_bank_statement.py
  account_statement_import_camt/views/account_bank_statement_import.xml
  setup/account_statement_import_camt/odoo/addons/account_statement_import_camt
  setup/account_statement_import_camt/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#610 [16.0][FIX] account_statement_import_file: Rename file_import selection value to file_import_oca
  account_statement_import_file/__manifest__.py
  account_statement_import_file/migrations/16.0.1.0.1/post-migration.py
  account_statement_import_file/models/account_journal.py
  account_statement_import_file/views/account_journal.xml
  account_statement_import_file/wizard/account_statement_import.py
Labels: approved, bot is merging ⏳

#566 [15.0][MIG] account_statement_import_file_reconciliation_widget
  account_statement_import_file_reconciliation_widget/README.rst
  account_statement_import_file_reconciliation_widget/__init__.py
  account_statement_import_file_reconciliation_widget/__manifest__.py
  account_statement_import_file_reconciliation_widget/i18n/account_statement_import_file_reconciliation_widget.pot
  account_statement_import_file_reconciliation_widget/i18n/fr.po
  account_statement_import_file_reconciliation_widget/readme/CONTRIBUTORS.rst
  account_statement_import_file_reconciliation_widget/readme/DESCRIPTION.rst
  account_statement_import_file_reconciliation_widget/readme/INSTALL.rst
  account_statement_import_file_reconciliation_widget/static/description/bank_statement_import_start_reconcile.png
  account_statement_import_file_reconciliation_widget/static/description/icon.png
  account_statement_import_file_reconciliation_widget/static/description/index.html
  account_statement_import_file_reconciliation_widget/wizards/__init__.py
  account_statement_import_file_reconciliation_widget/wizards/account_statement_import.py
  account_statement_import_file_reconciliation_widget/wizards/account_statement_import_view.xml
  setup/account_statement_import_file_reconciliation_widget/odoo/addons/account_statement_import_file_reconciliation_widget
  setup/account_statement_import_file_reconciliation_widget/setup.py
Labels: approved, bot is merging ⏳, no stale
