Repository OCA/bank-statement-import, pull requests merged in 2023-12, with the labels that each got.

#642 [13.0][UPD] account_bank_statement_import_online_paypal: new paypal event_code, T0403
  account_bank_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
Labels: approved, bot is merging ⏳

#650 [15.0][FIX] account_statement_import_online_gocardless: Unique ID fallback
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
Labels: approved, bot is merging ⏳

#652 [15.0][FIX] account_statement_import_online_gocardless: Fallback to journal company
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
Labels: bot is merging ⏳

#643 [16.0][IMP] account_statement_import_online_paypal: new paypal event_codes
  account_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
Labels: approved, ready to merge, bot is merging ⏳

#644 [15.0][IMP] account_statement_import_online_paypal: new paypal event_codes
  account_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
Labels: approved, ready to merge, bot is merging ⏳

#646 [13.0][IMP] account_bank_statement_import_online_paypal: new paypal event_codes
  account_bank_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
Labels: bot is merging ⏳
