Repository OCA/bank-statement-import, pull requests merged in 2024-12, with the labels that each got.

#743 [17.0] [FW-PORT] account_statement_import_sheet_file: additional mapping controls
  account_statement_import_sheet_file/README.rst
  account_statement_import_sheet_file/models/account_statement_import_sheet_mapping.py
  account_statement_import_sheet_file/models/account_statement_import_sheet_parser.py
  account_statement_import_sheet_file/readme/CONTRIBUTORS.md
  account_statement_import_sheet_file/static/description/index.html
  account_statement_import_sheet_file/tests/fixtures/empty_lines_statement.csv
  account_statement_import_sheet_file/tests/fixtures/sample_statement_offsets.xlsx
  account_statement_import_sheet_file/tests/test_account_statement_import_sheet_file.py
  account_statement_import_sheet_file/views/account_statement_import_sheet_mapping.xml
Labels: approved, bot is merging ⏳

#746 [16.0][FIX] account_statement_import_online_gocardless : fix typing error…
  account_statement_import_online_gocardless/wizards/online_bank_statement_provider_existing.py
Labels: bot is merging ⏳

#735 [18.0][MIG] account_statement_import_base: Migration to 18.0
  account_statement_import_base/README.rst
  account_statement_import_base/__init__.py
  account_statement_import_base/__manifest__.py
  account_statement_import_base/i18n/account_statement_import_base.pot
  account_statement_import_base/i18n/ca.po
  account_statement_import_base/i18n/es.po
  account_statement_import_base/i18n/fr.po
  account_statement_import_base/i18n/hr.po
  account_statement_import_base/i18n/it.po
  account_statement_import_base/i18n/pt_BR.po
  account_statement_import_base/i18n/zh_CN.po
  account_statement_import_base/models/__init__.py
  account_statement_import_base/models/account_bank_statement_line.py
  account_statement_import_base/models/account_journal.py
  account_statement_import_base/pyproject.toml
  account_statement_import_base/readme/CONTRIBUTORS.md
  account_statement_import_base/readme/DESCRIPTION.md
  account_statement_import_base/static/description/icon.png
  account_statement_import_base/static/description/index.html
  account_statement_import_base/views/account_bank_statement_line.xml
  checklog-odoo.cfg
Labels: approved, ready to merge, bot is merging ⏳

#730 [16][FIX] account_statement_import_online_paypal : search transaction with a 1 second margin to ensure it is found
  account_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
Labels: approved, ready to merge, bot is merging ⏳

#729 [16.0][FIX] account_statement_import_base: sanitized acc number
  account_statement_import_base/models/account_journal.py
Labels: approved, bot is merging ⏳

#754 [16.0][IMP] account_statement_import_online: add option to enable or disable statement creation.
  account_statement_import_online/models/online_bank_statement_provider.py
  account_statement_import_online/tests/test_account_bank_statement_import_online.py
  account_statement_import_online/views/online_bank_statement_provider.xml
Labels: approved, bot is merging ⏳

#695 [17.0][MIG] account_statement_import_ofx
  account_statement_import_ofx/README.rst
  account_statement_import_ofx/__init__.py
  account_statement_import_ofx/__manifest__.py
  account_statement_import_ofx/i18n/account_bank_statement_import_ofx.pot
  account_statement_import_ofx/i18n/account_statement_import_ofx.pot
  account_statement_import_ofx/i18n/de.po
  account_statement_import_ofx/i18n/es.po
  account_statement_import_ofx/i18n/es_AR.po
  account_statement_import_ofx/i18n/fi.po
  account_statement_import_ofx/i18n/fr.po
  account_statement_import_ofx/i18n/fr_CH.po
  account_statement_import_ofx/i18n/fr_FR.po
  account_statement_import_ofx/i18n/gl.po
  account_statement_import_ofx/i18n/it.po
  account_statement_import_ofx/i18n/lt_LT.po
  account_statement_import_ofx/i18n/nb_NO.po
  account_statement_import_ofx/i18n/nl.po
  account_statement_import_ofx/i18n/pt_BR.po
  account_statement_import_ofx/i18n/pt_PT.po
  account_statement_import_ofx/i18n/sl.po
  account_statement_import_ofx/models/__init__.py
  account_statement_import_ofx/models/account_journal.py
  account_statement_import_ofx/pyproject.toml
  account_statement_import_ofx/readme/CONTRIBUTORS.md
  account_statement_import_ofx/readme/DESCRIPTION.md
  account_statement_import_ofx/readme/INSTALL.md
  account_statement_import_ofx/static/description/icon.png
  account_statement_import_ofx/static/description/index.html
  account_statement_import_ofx/tests/__init__.py
  account_statement_import_ofx/tests/test_import_bank_statement.py
  account_statement_import_ofx/tests/test_ofx_file/test_ofx.ofx
  account_statement_import_ofx/tests/test_ofx_file/test_ofx_iban.ofx
  account_statement_import_ofx/tests/test_ofx_file/test_ofx_wrong.ofx
  account_statement_import_ofx/wizard/__init__.py
  account_statement_import_ofx/wizard/account_statement_import.py
  account_statement_import_ofx/wizard/account_statement_import.xml
  requirements.txt
Labels: approved, bot is merging ⏳
