Repository OCA/bank-statement-import, pull requests merged in 2024-05, with the labels that each got.

#690 [15.0][FIX] account_statement_import_online: Avoid error in journal unlink test
  account_statement_import_online/tests/test_account_bank_statement_import_online.py
Labels: approved, bot is merging ⏳

#688 [14.0][IMP]account_statement_import_txt_xlsx: additional mapping controls
  account_statement_import_txt_xlsx/README.rst
  account_statement_import_txt_xlsx/models/account_statement_import_sheet_mapping.py
  account_statement_import_txt_xlsx/models/account_statement_import_sheet_parser.py
  account_statement_import_txt_xlsx/readme/CONTRIBUTORS.rst
  account_statement_import_txt_xlsx/static/description/index.html
  account_statement_import_txt_xlsx/tests/fixtures/empty_lines_statement.csv
  account_statement_import_txt_xlsx/tests/fixtures/sample_statement_offsets.xlsx
  account_statement_import_txt_xlsx/tests/test_account_statement_import_txt_xlsx.py
  account_statement_import_txt_xlsx/views/account_statement_import_sheet_mapping.xml
Labels: bot is merging ⏳

#693 [16.0][FIX] account_statement_import_sheet_file: Remove empty lines with spaces
  account_statement_import_sheet_file/models/account_statement_import_sheet_parser.py
  account_statement_import_sheet_file/tests/fixtures/sample_statement_en_empty_values.xlsx
  account_statement_import_sheet_file/tests/test_account_statement_import_sheet_file.py
Labels: approved, merged 🎉

#651 [13.0][IMP] *_online_paypal: make sure unique_import_id within download is unique...
  account_bank_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
  account_bank_statement_import_online_paypal/tests/test_account_bank_statement_import_online_paypal.py
Labels: approved, bot is merging ⏳, stale

#654 [17.0][MIG] account_statement_import_sheet_file: Migration to 17.0
  README.md
  account_statement_import_sheet_file/README.rst
  account_statement_import_sheet_file/__init__.py
  account_statement_import_sheet_file/__manifest__.py
  account_statement_import_sheet_file/data/map_data.xml
  account_statement_import_sheet_file/i18n/account_statement_import_sheet_file.pot
  account_statement_import_sheet_file/i18n/es.po
  account_statement_import_sheet_file/i18n/es_AR.po
  account_statement_import_sheet_file/i18n/it.po
  account_statement_import_sheet_file/i18n/nl.po
  account_statement_import_sheet_file/i18n/pt.po
  account_statement_import_sheet_file/i18n/tr.po
  account_statement_import_sheet_file/i18n/zh_CN.po
  account_statement_import_sheet_file/models/__init__.py
  account_statement_import_sheet_file/models/account_journal.py
  account_statement_import_sheet_file/models/account_statement_import.py
  account_statement_import_sheet_file/models/account_statement_import_sheet_mapping.py
  account_statement_import_sheet_file/models/account_statement_import_sheet_parser.py
  account_statement_import_sheet_file/pyproject.toml
  account_statement_import_sheet_file/readme/CONFIGURE.md
  account_statement_import_sheet_file/readme/CONTRIBUTORS.md
  account_statement_import_sheet_file/readme/DESCRIPTION.md
  account_statement_import_sheet_file/readme/HISTORY.md
  account_statement_import_sheet_file/readme/USAGE.md
  account_statement_import_sheet_file/security/ir.model.access.csv
  account_statement_import_sheet_file/static/description/icon.png
  account_statement_import_sheet_file/static/description/index.html
  account_statement_import_sheet_file/tests/__init__.py
  account_statement_import_sheet_file/tests/fixtures/balance.csv
  account_statement_import_sheet_file/tests/fixtures/debit_credit.csv
  account_statement_import_sheet_file/tests/fixtures/debit_credit_amount.csv
  account_statement_import_sheet_file/tests/fixtures/empty_statement_en.csv
  account_statement_import_sheet_file/tests/fixtures/empty_statement_en.xlsx
  account_statement_import_sheet_file/tests/fixtures/meta_data_separated_credit_debit.csv
  account_statement_import_sheet_file/tests/fixtures/meta_data_separated_credit_debit.xlsx
  account_statement_import_sheet_file/tests/fixtures/multi_currency.csv
  account_statement_import_sheet_file/tests/fixtures/original_currency.csv
  account_statement_import_sheet_file/tests/fixtures/original_currency_empty.csv
  account_statement_import_sheet_file/tests/fixtures/original_currency_no_header.csv
  account_statement_import_sheet_file/tests/fixtures/sample_statement_credit_card_inverse_sign_en.csv
  account_statement_import_sheet_file/tests/fixtures/sample_statement_en.csv
  account_statement_import_sheet_file/tests/fixtures/sample_statement_en.xlsx
  account_statement_import_sheet_file/tests/fixtures/sample_statement_en_empty_values.xlsx
  account_statement_import_sheet_file/tests/test_account_statement_import_sheet_file.py
  account_statement_import_sheet_file/views/account_journal_views.xml
  account_statement_import_sheet_file/views/account_statement_import.xml
  account_statement_import_sheet_file/views/account_statement_import_sheet_mapping.xml
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#700 [14.0][FIX] account_statement_import: Do not overwrite journal active_id
  account_statement_import/wizard/account_statement_import.py
Labels: approved, bot is merging ⏳
