Repository OCA/bank-statement-import, pull requests merged in 2024-02, with the labels that each got.

#664 [16.0][IMP] account_statement_import_online: Add debug wizard
  account_statement_import_online/README.rst
  account_statement_import_online/__manifest__.py
  account_statement_import_online/models/online_bank_statement_provider.py
  account_statement_import_online/security/ir.model.access.csv
  account_statement_import_online/static/description/index.html
  account_statement_import_online/wizards/__init__.py
  account_statement_import_online/wizards/online_bank_statement_pull_debug.py
  account_statement_import_online/wizards/online_bank_statement_pull_debug.xml
  account_statement_import_online/wizards/online_bank_statement_pull_wizard.py
  account_statement_import_online/wizards/online_bank_statement_pull_wizard.xml
  account_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
  account_statement_import_online_ponto/tests/test_account_statement_import_online_ponto.py
Labels: bot is merging ⏳

#660 [15.0][IMP] account_statement_import_online: Add debug wizard
  account_statement_import_online/README.rst
  account_statement_import_online/__manifest__.py
  account_statement_import_online/models/online_bank_statement_provider.py
  account_statement_import_online/security/ir.model.access.csv
  account_statement_import_online/static/description/index.html
  account_statement_import_online/wizards/__init__.py
  account_statement_import_online/wizards/online_bank_statement_pull_debug.py
  account_statement_import_online/wizards/online_bank_statement_pull_debug.xml
  account_statement_import_online/wizards/online_bank_statement_pull_wizard.py
  account_statement_import_online/wizards/online_bank_statement_pull_wizard.xml
Labels: bot is merging ⏳

#665 [15.0][FIX] account_statement_import_online_gocardless: Payment reference extraction
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
Labels: bot is merging ⏳

#658 [14.0] repo update fix pre-commit
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  account_statement_import/demo/partner_bank.xml
  account_statement_import/i18n/account_statement_import.pot
  account_statement_import/i18n/ar.po
  account_statement_import/i18n/da.po
  account_statement_import/i18n/de.po
  account_statement_import/i18n/et.po
  account_statement_import/i18n/fi.po
  account_statement_import/i18n/he.po
  account_statement_import/i18n/hr.po
  account_statement_import/i18n/hu.po
  account_statement_import/i18n/ko.po
  account_statement_import/i18n/lt.po
  account_statement_import/i18n/mn.po
  account_statement_import/i18n/pl.po
  account_statement_import/i18n/ru.po
  account_statement_import/i18n/sk.po
  account_statement_import/i18n/tr.po
  account_statement_import/i18n/uk.po
  account_statement_import/i18n/vi.po
  account_statement_import/i18n/zh_CN.po
  account_statement_import/i18n/zh_TW.po
  account_statement_import/wizard/account_statement_import.py
Labels: approved, bot is merging ⏳

#647 [17.0][MIG] account_statement_import_base: Migration to 17.0
  account_statement_import_base/README.rst
  account_statement_import_base/__init__.py
  account_statement_import_base/__manifest__.py
  account_statement_import_base/i18n/account_statement_import_base.pot
  account_statement_import_base/i18n/ca.po
  account_statement_import_base/i18n/es.po
  account_statement_import_base/i18n/fr.po
  account_statement_import_base/i18n/hr.po
  account_statement_import_base/i18n/pt_BR.po
  account_statement_import_base/models/__init__.py
  account_statement_import_base/models/account_bank_statement_line.py
  account_statement_import_base/models/account_journal.py
  account_statement_import_base/pyproject.toml
  account_statement_import_base/readme/CONTRIBUTORS.md
  account_statement_import_base/readme/DESCRIPTION.md
  account_statement_import_base/static/description/icon.png
  account_statement_import_base/static/description/index.html
  account_statement_import_base/views/account_bank_statement_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#668 [16.0][IMP] account_statement_import_online: only update journal when online service is set
  account_statement_import_online/models/account_journal.py
Labels: approved, bot is merging ⏳

#663 [16.0][IMP] account_statement_import_sheet_file: add field amount_inverse_sign_column
  account_statement_import_sheet_file/models/account_statement_import_sheet_mapping.py
  account_statement_import_sheet_file/models/account_statement_import_sheet_parser.py
  account_statement_import_sheet_file/tests/fixtures/sample_statement_credit_card_inverse_sign_en.csv
  account_statement_import_sheet_file/tests/test_account_statement_import_sheet_file.py
  account_statement_import_sheet_file/views/account_statement_import_sheet_mapping.xml
Labels: approved, ready to merge, bot is merging ⏳

#601 [14.0][MIG] account_statement_import_online_wise : Migration to 14.0
  account_statement_import_online_wise/README.rst
  account_statement_import_online_wise/__init__.py
  account_statement_import_online_wise/__manifest__.py
  account_statement_import_online_wise/i18n/account_bank_statement_import_online_transferwise.pot
  account_statement_import_online_wise/i18n/nl.po
  account_statement_import_online_wise/models/__init__.py
  account_statement_import_online_wise/models/online_bank_statement_provider_transferwise.py
  account_statement_import_online_wise/readme/CONFIGURE.rst
  account_statement_import_online_wise/readme/CONTRIBUTORS.rst
  account_statement_import_online_wise/readme/DESCRIPTION.rst
  account_statement_import_online_wise/readme/USAGE.rst
  account_statement_import_online_wise/static/description/icon.png
  account_statement_import_online_wise/static/description/index.html
  account_statement_import_online_wise/tests/__init__.py
  account_statement_import_online_wise/tests/test_account_bank_statement_import_online_transferwise.py
  account_statement_import_online_wise/tests/test_account_statement_import_online_transferwise.py
  account_statement_import_online_wise/views/online_bank_statement_provider.xml
  requirements.txt
  setup/account_statement_import_online_wise/odoo/addons/account_statement_import_online_wise
  setup/account_statement_import_online_wise/setup.py
Labels: bot is merging ⏳

#648 [16.0][FIX] models/online_bank_statement_provider_ponto.py: prevent a…
  account_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
Labels: approved, ready to merge, bot is merging ⏳

#670 [15.0][IMP] account_statement_import_online_gocardless: Reuse requisition from other provider
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
Labels: approved, bot is merging ⏳

#671 [16.0][IMP] account_statement_import_online_gocardless: Reuse requisition from other provider
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
Labels: approved, bot is merging ⏳
