Repository OCA/bank-statement-import, pull requests merged in 2024-08, with the labels that each got.

#686 [16.0][FIX] account_statement_import_online_gocardless: IBAN comparison
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
  account_statement_import_online_gocardless/tests/test_account_statement_import_online_gocardless.py
Labels: approved, ready to merge, bot is merging ⏳

#712 [16.0][FIX] account_statement_import_online_gocardless: Bugs after the refactoring
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
Labels: bot is merging ⏳

#713 [16.0][FIX] account_statement_import_online_gocardless: Slash at the end
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
Labels: bot is merging ⏳

#645 [14.0][IMP] account_statement_import_online_paypal: new paypal event_codes
  account_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
Labels: approved, bot is merging ⏳
