Repository OCA/bank-statement-import, pull requests merged in 2025-07, with the labels that each got.

#772 [18.0][MIG] account_statement_import_online_ponto
  account_statement_import_online_ponto/README.rst
  account_statement_import_online_ponto/__init__.py
  account_statement_import_online_ponto/__manifest__.py
  account_statement_import_online_ponto/i18n/account_statement_import_online_ponto.pot
  account_statement_import_online_ponto/i18n/ca.po
  account_statement_import_online_ponto/i18n/es.po
  account_statement_import_online_ponto/i18n/it.po
  account_statement_import_online_ponto/i18n/nl.po
  account_statement_import_online_ponto/models/__init__.py
  account_statement_import_online_ponto/models/online_bank_statement_provider_ponto.py
  account_statement_import_online_ponto/models/ponto_interface.py
  account_statement_import_online_ponto/pyproject.toml
  account_statement_import_online_ponto/readme/CONFIGURE.md
  account_statement_import_online_ponto/readme/CONTRIBUTORS.md
  account_statement_import_online_ponto/readme/DESCRIPTION.md
  account_statement_import_online_ponto/readme/USAGE.md
  account_statement_import_online_ponto/static/description/icon.png
  account_statement_import_online_ponto/static/description/index.html
  account_statement_import_online_ponto/tests/__init__.py
  account_statement_import_online_ponto/tests/test_account_statement_import_online_ponto.py
  account_statement_import_online_ponto/tests/test_ponto_interface.py
  account_statement_import_online_ponto/views/online_bank_statement_provider.xml
Labels: approved, ready to merge, bot is merging ⏳

#808 [17.0][FIX] account_statement_import_online_gocardless: token refresh/renew behavior
  account_statement_import_online_gocardless/README.rst
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
  account_statement_import_online_gocardless/readme/CONTRIBUTORS.md
  account_statement_import_online_gocardless/static/description/index.html
Labels: bot is merging ⏳

#809 [16.0][IMP] account_statement_import_online_gocardless: Be aware of rate limits
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
Labels: approved, bot is merging ⏳

#807 [16.0][FIX] account_statement_import_online_gocardless: Don't reuse other account agreement
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
Labels: approved, bot is merging ⏳
