Repository OCA/bank-statement-import, pull requests merged in 2025-02, with the labels that each got.

#734 [17.0][MIG] account_statement_import_camt54: Migration to 17.0
  account_statement_import_camt54/README.rst
  account_statement_import_camt54/__init__.py
  account_statement_import_camt54/__manifest__.py
  account_statement_import_camt54/i18n/account_statement_import_camt54.pot
  account_statement_import_camt54/i18n/es.po
  account_statement_import_camt54/i18n/it.po
  account_statement_import_camt54/i18n/nl.po
  account_statement_import_camt54/migrations/17.0.1.0.0/pre-migrate.py
  account_statement_import_camt54/models/__init__.py
  account_statement_import_camt54/models/account_journal.py
  account_statement_import_camt54/models/account_statement_import.py
  account_statement_import_camt54/models/parser.py
  account_statement_import_camt54/pyproject.toml
  account_statement_import_camt54/readme/CONTRIBUTORS.md
  account_statement_import_camt54/readme/CREDITS.md
  account_statement_import_camt54/readme/DESCRIPTION.md
  account_statement_import_camt54/static/description/icon.png
  account_statement_import_camt54/static/description/index.html
  account_statement_import_camt54/tests/__init__.py
  account_statement_import_camt54/tests/test_get_partner_ref.py
  account_statement_import_camt54/tests/test_statement.py
  account_statement_import_camt54/views/account_journal_view.xml
Labels: approved, bot is merging ⏳

#766 [16.0][imp][account_statement_import_online_gocardless]: add hook to construct to unique transaction id
  account_statement_import_online_gocardless/models/online_bank_statement_provider.py
Labels: approved, bot is merging ⏳

#768 [16.0][FIX] account_statement_import_online*: Post-install test + fallback to load CoA
  account_statement_import_online/tests/test_account_bank_statement_import_online.py
  account_statement_import_online_gocardless/tests/test_account_statement_import_online_gocardless.py
Labels: bot is merging ⏳

#764 [14.0][IMP] ensure currency name comparison is case-insensitive
  account_statement_import_txt_xlsx/models/account_statement_import_sheet_parser.py
Labels: approved, ready to merge, bot is merging ⏳

#765 [17.0][MIG] account_statement_import_paypal
  account_statement_import_paypal/README.rst
  account_statement_import_paypal/__init__.py
  account_statement_import_paypal/__manifest__.py
  account_statement_import_paypal/data/maps.xml
  account_statement_import_paypal/i18n/account_statement_import_paypal.pot
  account_statement_import_paypal/i18n/es.po
  account_statement_import_paypal/i18n/es_AR.po
  account_statement_import_paypal/i18n/it.po
  account_statement_import_paypal/models/__init__.py
  account_statement_import_paypal/models/account_journal.py
  account_statement_import_paypal/models/account_statement_import.py
  account_statement_import_paypal/models/account_statement_import_paypal_mapping.py
  account_statement_import_paypal/models/account_statement_import_paypal_parser.py
  account_statement_import_paypal/pyproject.toml
  account_statement_import_paypal/readme/CONFIGURE.md
  account_statement_import_paypal/readme/CONTRIBUTORS.md
  account_statement_import_paypal/readme/DESCRIPTION.md
  account_statement_import_paypal/readme/HISTORY.md
  account_statement_import_paypal/readme/USAGE.md
  account_statement_import_paypal/security/ir.model.access.csv
  account_statement_import_paypal/static/description/icon.png
  account_statement_import_paypal/static/description/index.html
  account_statement_import_paypal/tests/__init__.py
  account_statement_import_paypal/tests/fixtures/activity_en.csv
  account_statement_import_paypal/tests/fixtures/empty_activity.csv
  account_statement_import_paypal/tests/fixtures/statement_en.csv
  account_statement_import_paypal/tests/fixtures/statement_es.csv
  account_statement_import_paypal/tests/test_account_statement_import_paypal.py
  account_statement_import_paypal/views/account_statement_import.xml
  account_statement_import_paypal/views/account_statement_import_paypal_mapping.xml
  account_statement_import_paypal/wizards/__init__.py
  account_statement_import_paypal/wizards/account_statement_import_paypal_mapping_wizard.py
  account_statement_import_paypal/wizards/account_statement_import_paypal_mapping_wizard.xml
Labels: approved, ready to merge, bot is merging ⏳
