Repository OCA/bank-statement-import, pull requests merged in 2025-04, with the labels that each got.

#792 [17.0] [IMP] account_statement_import_file: Allow to pass context on vals
  account_statement_import_file/wizard/account_statement_import.py
Labels: approved, bot is merging ⏳

#773 [15.0][FIX] account_statement_import_txt_xlsx: currency comparison case-insensitive
  account_statement_import_txt_xlsx/models/account_statement_import_sheet_parser.py
Labels: approved, bot is merging ⏳

#737 [18.0][MIG] account_statement_import_camt: Migration to 18.0
  account_statement_import_camt/README.rst
  account_statement_import_camt/__init__.py
  account_statement_import_camt/__manifest__.py
  account_statement_import_camt/i18n/account_statement_import_camt.pot
  account_statement_import_camt/i18n/de.po
  account_statement_import_camt/i18n/es.po
  account_statement_import_camt/i18n/fa.po
  account_statement_import_camt/i18n/fi.po
  account_statement_import_camt/i18n/fr.po
  account_statement_import_camt/i18n/fr_CH.po
  account_statement_import_camt/i18n/gl.po
  account_statement_import_camt/i18n/hr.po
  account_statement_import_camt/i18n/it.po
  account_statement_import_camt/i18n/lt_LT.po
  account_statement_import_camt/i18n/nb_NO.po
  account_statement_import_camt/i18n/nl.po
  account_statement_import_camt/i18n/pt_BR.po
  account_statement_import_camt/i18n/pt_PT.po
  account_statement_import_camt/i18n/sl.po
  account_statement_import_camt/models/__init__.py
  account_statement_import_camt/models/account_journal.py
  account_statement_import_camt/models/account_statement_import.py
  account_statement_import_camt/models/account_statement_import_camt_parser.py
  account_statement_import_camt/pyproject.toml
  account_statement_import_camt/readme/CONTRIBUTORS.md
  account_statement_import_camt/readme/CREDITS.md
  account_statement_import_camt/readme/DESCRIPTION.md
  account_statement_import_camt/readme/newsfragment/1_verbose_narration.feature
  account_statement_import_camt/static/description/icon.png
  account_statement_import_camt/static/description/index.html
  account_statement_import_camt/tests/__init__.py
  account_statement_import_camt/tests/samples/golden-camt053-no-ntry.pydata
  account_statement_import_camt/tests/samples/golden-camt053-txdtls.pydata
  account_statement_import_camt/tests/samples/golden-camt053.pydata
  account_statement_import_camt/tests/samples/golden-camt054.pydata
  account_statement_import_camt/tests/samples/test-camt053
  account_statement_import_camt/tests/samples/test-camt053-no-ntry
  account_statement_import_camt/tests/samples/test-camt053-txdtls
  account_statement_import_camt/tests/samples/test-camt053.zip
  account_statement_import_camt/tests/samples/test-camt054
  account_statement_import_camt/tests/test_import_bank_statement.py
  account_statement_import_camt/views/account_bank_statement_import.xml
Labels: approved, ready to merge, bot is merging ⏳

#738 [18.0][MIG] account_statement_import_camt54: Migration to 18.0
  account_statement_import_camt54/README.rst
  account_statement_import_camt54/__init__.py
  account_statement_import_camt54/__manifest__.py
  account_statement_import_camt54/i18n/account_statement_import_camt54.pot
  account_statement_import_camt54/i18n/es.po
  account_statement_import_camt54/i18n/it.po
  account_statement_import_camt54/i18n/nl.po
  account_statement_import_camt54/models/__init__.py
  account_statement_import_camt54/models/account_journal.py
  account_statement_import_camt54/models/account_statement_import.py
  account_statement_import_camt54/models/parser.py
  account_statement_import_camt54/pyproject.toml
  account_statement_import_camt54/readme/CONTRIBUTORS.md
  account_statement_import_camt54/readme/CREDITS.md
  account_statement_import_camt54/readme/DESCRIPTION.md
  account_statement_import_camt54/static/description/icon.png
  account_statement_import_camt54/static/description/index.html
  account_statement_import_camt54/tests/__init__.py
  account_statement_import_camt54/tests/test_get_partner_ref.py
  account_statement_import_camt54/tests/test_statement.py
  account_statement_import_camt54/views/account_journal_view.xml
Labels: approved, bot is merging ⏳

#793 [18.0] [IMP] account_statement_import_file: Allow to pass context on vals
  account_statement_import_file/wizard/account_statement_import.py
Labels: bot is merging ⏳

#750 [16.0] [IMP] account_statement_import_file: file_import_oca's label to 'OCA Import'
  account_statement_import_file/models/account_journal.py
Labels: approved, bot is merging ⏳, stale
